#!/bin/bash
set -e

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
NC='\033[0m' # No Color

echo -e "${BLUE}"
echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║                    SYNCHRONO CITY SETUP                       ║"
echo "║                                                               ║"
echo "║   Chosen Presence. Sovereign Infrastructure. Portable Community."
echo "╚═══════════════════════════════════════════════════════════════╝"
echo -e "${NC}"

# Check prerequisites
echo -e "${YELLOW}Checking prerequisites...${NC}"

if ! command -v docker &> /dev/null; then
    echo -e "${RED}Error: Docker is not installed.${NC}"
    echo "Install Docker: https://docs.docker.com/get-docker/"
    exit 1
fi

if ! docker compose version &> /dev/null; then
    echo -e "${RED}Error: Docker Compose is not installed.${NC}"
    echo "Install Docker Compose: https://docs.docker.com/compose/install/"
    exit 1
fi

echo -e "${GREEN}✓ Docker and Docker Compose are installed${NC}"

# Check if .env.docker already exists
if [ -f ".env.docker" ]; then
    echo -e "${YELLOW}.env.docker already exists.${NC}"
    read -p "Overwrite existing configuration? (y/N): " -n 1 -r
    echo
    if [[ ! $REPLY =~ ^[Yy]$ ]]; then
        echo "Keeping existing configuration."
        exit 0
    fi
    # Backup existing file
    cp .env.docker .env.docker.backup
    echo -e "${GREEN}✓ Backed up existing .env.docker to .env.docker.backup${NC}"
fi

COMPOSE_CMD=(docker compose --env-file .env.docker)

# Generate random hex string
generate_hex() {
    local length=$1
    openssl rand -hex $length
}

# Generate Nostr keypair (simple implementation using openssl)
generate_nostr_keypair() {
    # Generate 32 bytes of random data for private key
    local privkey_hex=$(openssl rand -hex 32)

    # For now, just output the hex private key
    # In production, you'd use a proper Nostr library to derive npub/nsec
    echo "$privkey_hex"
}

echo ""
echo -e "${BLUE}Generating configuration...${NC}"

# Generate secrets
SESSION_SECRET=$(generate_hex 32)
CSRF_SECRET=$(generate_hex 32)
LIVEKIT_API_KEY="key$(generate_hex 4)"
LIVEKIT_API_SECRET=$(generate_hex 32)
OPERATOR_PRIVKEY=$(generate_nostr_keypair)

# Relay info
RELAY_NAME="${RELAY_NAME:-Synchrono City}"
RELAY_SLUG="${RELAY_SLUG:-synchrono-city}"

# Mapbox prompt
echo ""
echo -e "${YELLOW}Mapbox Configuration (optional)${NC}"
echo "A Mapbox token is required for map tiles. Without it, the map will be blank."
echo "Get a free token at: https://account.mapbox.com/access-tokens/"
read -p "Enter Mapbox access token (or press Enter to skip): " MAPBOX_TOKEN

if [ -z "$MAPBOX_TOKEN" ]; then
    MAPBOX_TOKEN=""
    MAPBOX_STYLE=""
    echo -e "${YELLOW}⚠ No Mapbox token - map will be blank. You can add one later.${NC}"
else
    MAPBOX_STYLE="mapbox://styles/mapbox/dark-v11"
    echo -e "${GREEN}✓ Mapbox token set${NC}"
fi

# Create .env.docker
echo ""
echo -e "${BLUE}Creating .env.docker...${NC}"

cat > .env.docker << EOF
# Generated by setup.sh on $(date -u +"%Y-%m-%d %H:%M:%S UTC")

# Database
POSTGRES_DB=synchrono_city
POSTGRES_USER=postgres
POSTGRES_PASSWORD=postgres
DATABASE_URL=postgres://postgres:postgres@postgres:5432/synchrono_city?sslmode=disable
DB_MAX_OPEN_CONNS=25
DB_MAX_IDLE_CONNS=5
DB_CONN_MAX_LIFETIME=30m

# LiveKit Media Server
LIVEKIT_API_KEY=${LIVEKIT_API_KEY}
LIVEKIT_API_SECRET=${LIVEKIT_API_SECRET}
LIVEKIT_URL=ws://localhost:17880

# Operator Identity (IMPORTANT: Save your private key!)
PRIMARY_OPERATOR_PUBKEY=${OPERATOR_PRIVKEY}
RELAY_NAME=${RELAY_NAME}
RELAY_SLUG=${RELAY_SLUG}
PRIMARY_RELAY_URL=ws://localhost:8080

# Session Security
SESSION_SECRET=${SESSION_SECRET}
SESSION_COOKIE_NAME=synchrono_city_session
SESSION_TTL=24h
SESSION_IDLE_TTL=4h
CSRF_SIGNING_SECRET=${CSRF_SECRET}

# Service Ports
PORT=3000
CONCIERGE_RELAY_AUTH_URL=http://concierge:3000/internal/relay/authorize

# Client Configuration
VITE_CONCIERGE_URL=http://localhost:3000
VITE_NOSTR_RELAY_URL=ws://localhost:8080
VITE_BLOSSOM_URL=http://localhost:3001
VITE_MAPBOX_ACCESS_TOKEN=${MAPBOX_TOKEN}
VITE_MAPBOX_STYLE_URL=${MAPBOX_STYLE}
EOF

echo -e "${GREEN}✓ Created .env.docker${NC}"

# Print operator key info
echo ""
echo -e "${BLUE}╔═══════════════════════════════════════════════════════════════╗${NC}"
echo -e "${BLUE}║               OPERATOR CREDENTIALS - SAVE THESE!              ║${NC}"
echo -e "${BLUE}╠═══════════════════════════════════════════════════════════════╣${NC}"
echo -e "${YELLOW}║${NC}"
echo -e "${YELLOW}║  Your Operator Private Key (hex):${NC}"
echo -e "${GREEN}║  ${OPERATOR_PRIVKEY}${NC}"
echo -e "${YELLOW}║${NC}"
echo -e "${RED}║  ⚠ IMPORTANT: Save this key securely! You'll need it to${NC}"
echo -e "${RED}║  authenticate as the relay operator. This key is NOT stored${NC}"
echo -e "${RED}║  anywhere except in .env.docker on this machine.${NC}"
echo -e "${YELLOW}║${NC}"
echo -e "${BLUE}╚═══════════════════════════════════════════════════════════════╝${NC}"

# Offer to start
echo ""
read -p "Start Synchrono City now? (Y/n): " -n 1 -r
echo
if [[ ! $REPLY =~ ^[Nn]$ ]]; then
    echo ""
    echo -e "${BLUE}Building and starting services...${NC}"
    "${COMPOSE_CMD[@]}" up -d --build

    echo ""
    echo -e "${GREEN}✓ Synchrono City is starting!${NC}"
    echo ""
    echo -e "${BLUE}Services:${NC}"
    echo -e "  Client:     ${GREEN}http://localhost:5173${NC}"
    echo -e "  Relay:      ${GREEN}ws://localhost:8080${NC}"
    echo -e "  Concierge:  ${GREEN}http://localhost:3000${NC}"
    echo -e "  Blossom:    ${GREEN}http://localhost:3001${NC}"
    echo -e "  LiveKit:    ${GREEN}ws://localhost:17880${NC}"
    echo ""
    echo -e "${YELLOW}Next steps:${NC}"
    echo -e "  1. Open ${GREEN}http://localhost:5173${NC} in your browser"
    echo -e "  2. Import your operator key into a Nostr client"
    echo -e "  3. Access admin at ${GREEN}http://localhost:5173/app/settings${NC}"
    echo ""
    echo -e "Useful commands:"
    echo -e "  ${GREEN}${COMPOSE_CMD[*]} logs -f${NC}     Follow all logs"
    echo -e "  ${GREEN}${COMPOSE_CMD[*]} logs -f concierge${NC}  Follow concierge logs"
    echo -e "  ${GREEN}${COMPOSE_CMD[*]} down${NC}       Stop all services"
    echo -e "  ${GREEN}${COMPOSE_CMD[*]} up -d${NC}       Start services again"
else
    echo ""
    echo -e "${GREEN}Configuration complete!${NC}"
    echo -e "Run ${GREEN}${COMPOSE_CMD[*]} up -d${NC} to start when ready."
fi
