publicDomain: ""
databasePath: /data/sqlite.db

dashboard:
  enabled: true
  username: admin

storage:
  backend: local
  removeWhenNoOwners: false
  local:
    dir: /data/blobs
  rules:
    - type: "image/*"
      expiration: 1 week
    - type: "video/*"
      expiration: 5 days
    - type: "*"
      expiration: 2 days

upload:
  enabled: true
  requireAuth: true

media:
  enabled: true
  requireAuth: true
